
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false




