
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  # ===============================
  # = MAIL
  # ===============================
  mail:
    host: localhost
    password: emailpass
    username: emailuser
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 3025
          auth: false
          starttls:
            enable: false
            required: false



