server:
  port: ${PORT:5001}
  servlet:
    context-path: ${CONTEXT_PATH:}

amazonProperties:
  region: us-west-2
  endpointUrl: https://s3.us-west-2.amazonaws.com
  accessKey: ${AWS_ACCESS_KEY:}
  secretKey: ${AWS_SECRET:}
  bucketName: decapay
  smtpHost: ${AWS_SMTP_HOST:}
  smtpUserName: ${AWS_SMTP_USERNAME:}
  smtpPassword: ${AWS_SMTP_PASSWORD:}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:decapay}}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
