server:
  port: ${PORT:5000}
  servlet:
    context-path: ${CONTEXT_PATH:}

amazonProperties:
  region: us-west-2
  endpointUrl: https://s3.us-west-2.amazonaws.com
  accessKey: ${AWS_ACCESS_KEY:}
  secretKey: ${AWS_SECRET:}
  bucketName: decapay
  #smtp email config
  smtpHost: ${AWS_SMTP_HOST:}
  smtpUserName: ${AWS_SMTP_USERNAME:}
  smtpPassword: ${AWS_SMTP_PASSWORD:}

config.emailSender: cloud-smtp

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://decapay-api-db.crwrzhnx1ugs.us-east-2.rds.amazonaws.com:5432/decapay_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false

---
spring:
  flyway:
    enabled: true