version: 2.1
executors:
  java11:
    docker:
      - image: 'cimg/openjdk:11.0'
orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0 # ...with this image as the primary container; this is where all `steps` will run

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # store the version denoted by the POM onto the env
      - run: mkdir -p target
      - run: mvn dependency:go-offline
      - run: mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev '(^\[|Download)' > target/version.txt

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build artifacts
          command: |
            mvn package -Dspring.profiles.active=test
      - run:
          name: Create application source bundle
          command: |
            zip -r source_bundle.zip target/decapay.jar .platform Procfile
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target/version.txt #this is inside target dir inside work-dir
            - source_bundle.zip  #this is inside work-dir


workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X compile'
          executor: java11
  workflow:
    jobs:
      - build