name: Decapay CI
on:
  pull_request:
    branches: [ develop ]
           

jobs:
  build-and-push:
    name: Setup Java and run Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -Dspring.profiles.active=test

    